Sofia/cleanup condition expr
jetbrains-academy/introduction_to_python pull request #7
Opened 2021-06-02 15:28 UTC by sofiiako

2021-06-23 14:44 UTC, Geravant requested changes

2021-06-23 14:44 UTC, Geravant commented on Condition expressions/If statement/task.md
> +the execution of those other statements in some way. The `if`, `while` and `for` statements
We are nott actually talking in tterms of control flow here in the lesson, so we probably need o loose the mention of the loops and simplify the description

2021-06-23 14:44 UTC, Geravant commented on Condition expressions/If statement/task.md
> +specified code after checking if its expression is `True`. Python uses indentation
We can elaborate on the exact  indentation  type used here

2021-06-23 14:44 UTC, Geravant commented on Condition expressions/Else and elif statements/task.md
> +There can be zero or more `elif` parts, and the `else` part is optional. The keyword
We can mention them being substitute for a switch somewhere

2021-06-23 14:44 UTC, Geravant commented on Condition expressions/lesson-info.yaml
> +- Else and elif statements
Why are we losing the word part?

2021-06-23 14:44 UTC, Geravant commented on Data structures/Tuples/task-info.yaml
> +    length: 0
Do we need a placeholder withou a length? What are we trying to ask?

2021-06-23 14:44 UTC, Geravant commented on Introduction/Comments/task-info.yaml
>      placeholder_text: add new comment here
May be for a demonstraion purpose we can omit the number sign here

2021-06-23 17:05 UTC, sofiiako commented on Condition expressions/If statement/if_statement.py
> +if name == "John" or age == 17:  # check that name is "John" or age is 17. If so print next 2 lines.
It comes from the original version) But agreed

2021-06-29 12:54 UTC, Geravant approved these changes

2021-06-30 18:15 UTC, merged